//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLinks
{
    using System;
    using System.Collections.Generic;
    
    public partial class uservlog
    {
        public string usergmail { get; set; }
        public Nullable<int> vid { get; set; }
        public string appliedtime { get; set; }
    
        public virtual vacancy vacancy { get; set; }
    }
}
