//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLinks
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacancy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vacancy()
        {
            this.uservlogs = new HashSet<uservlog>();
        }
    
        public int vid { get; set; }
        public string j_title { get; set; }
        public string location { get; set; }
        public string salary { get; set; }
        public string workingday { get; set; }
        public string workingtime { get; set; }
        public string vdescription { get; set; }
        public string vpostdate { get; set; }
        public string vexpireddate { get; set; }
        public string companygmail { get; set; }
        public string companyphone { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uservlog> uservlogs { get; set; }
    }
}
